config/routes.rb
class RestrictedConstraint
  def matches?(request)
    request.path !~ /rails/
  end
end

Rails.application.routes.draw do
  root "phonebook#search"

  get '/', to: 'phonebook#search', as: 'search'
  get '/autocomplete', to: 'phonebook#autocomplete'

  scope :account do
    devise_for :users, path: "", path_names: {
      sign_in: 'login',
      sign_out: 'logout',
      registration: 'signup'
    }
  end

  namespace :api, :defaults => { :format => :json } do 
    namespace :v1 do
      resources :contacts, only: [:index, :show, :create, :destroy, :update], constraints: lambda { |req| ['json', 'xml', 'csv', 'vcf', 'png'].include?(req.format) }
      resource :help, only: [:show, :create, :destroy, :update], constraints: { format: 'html' }
      resource :user, only: [:show, :update], constraints: { format: 'json' }
    end 
  end

  namespace :admin do
    get '/', to: redirect { |p, r| "#{r.url.sub(/(\/)+$/,'')}/users" }

    resources :users, except: %i[show], path_names: { edit: '' }
    resources :contacts, except: %i[show], path_names: { edit: '' }
    resources :departments, except: %i[show], path_names: { edit: '' }
    resources :titles, except: %i[show], path_names: { edit: '' }
    resource :help
    resource :settings, only: %i[show update]
  end

  namespace :profile do
    resource :my_profile
    resources :my_contacts
    resource :settings
  end

  resources :exports, only: %i[index new create show]
  delete '/exports', to: 'exports#destroy_all'
  # resource :settings
  resource :helps, only: %i[show]

  resources :contacts, only: %i[show], path: '', constraints: lambda {|request| Contact.find_by_slug request.params[:id]}
  resources :departments, only: %i[show], path: '', constraints: lambda {|request| Department.find_by_slug request.params[:id]}
  
  get '*path', to: redirect("?q=%{path}"), constraints: RestrictedConstraint.new
end

app/models/department.rb
class Department < ApplicationRecord
  include Settings::DepartmentSearch
  include Slugged

  def initialize(args = {})
    args ||= {}
    args[:params] = init_params(args[:params]) if args[:params]
    super(args)
  end

  def update(args = {})
    args[:params] = init_params(args[:params]) if args[:params]
    super(args)
  end

  resourcify
  
  acts_as_nested_set

  has_many :contacts #, :include => :title, :order => ['titles.position', 'lastname']
  has_many :params, as: :paramable
  belongs_to :chief, class_name: "Contact", optional: true

  accepts_nested_attributes_for :params, reject_if: :all_blank, allow_destroy: true

  def slug_candidates
    [
      # [parent && parent.self_and_ancestors.map{|dep| dep.name}, :name],
      [:name],
      [:name, :id]
    ]
  end

  def abbrs
    abbrs = []
    departments = self_and_ancestors.map{|dep| !dep.name.blank? && dep.name.gsub(/[^а-яА-Я0-9a-zA-Z]+/, " ").split(' ')}
    # abbrs += departments.flatten if departments
    abbrs += departments.map do |d|
      deps1 = d.select{|val| val != val.upcase}.map{|val| val[0]}.join
      deps2 = d.select{|val| val != val.upcase && val.length > 2}.map{|val| val[0]}.join
      [deps1, deps2].select{|val| val.length > 1}
    end.flatten if departments
    abbrs
  end

  def to_s
    name
  end

  default_scope { order(lft: :asc) }

private

  def init_params(params)
    if params #&& params.is_a? Param
      ret = []
      params.each do |param|
        prm = Param.find_or_initialize_by(id: param[:id]) {|prm| prm.id = nil}
        prm.name, prm.value, prm.param_type = param[:name], param[:value], param[:type]
        prm.save unless prm.new_record?
        ret << prm unless (prm.name.blank? || prm.value.blank? || prm.param_type.blank?)
        prm.delete if prm.value.blank?
      end
    end
    ret || params
  end
end

app/controllers/admin/departments_controller.rb
class Admin::DepartmentsController < AdminController
  before_action :set_department, only: [:show, :edit, :update, :destroy]

  # GET /departments
  # GET /departments.json
  def index
    @departments = params[:parent] && (!params[:parent].empty? && Department.where("parent_id = ?", params[:parent]) || Department.roots) || Department.all
  end

  # GET /departments/1
  # GET /departments/1.json
  def show
  end

  # GET /departments/new
  def new
    @department = Department.new
  end

  # GET /departments/1/edit
  def edit
  end

  # POST /departments
  # POST /departments.json
  def create
    @department = Department.new(department_params)

    respond_to do |format|
      if @department.save
        format.html { redirect_to admin_departments_path, notice: 'Department was successfully created.' }
        format.json { render :show, status: :created, location: @department }
      else
        format.html { render :new }
        format.json { render json: @department.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /departments/1
  # PATCH/PUT /departments/1.json
  def update
    respond_to do |format|
      if @department.update(department_params)
        format.html { redirect_to admin_departments_path, notice: 'Department was successfully updated.' }
        format.json { render :show, status: :ok, location: @department }
      else
        format.html { render :edit }
        format.json { render json: @department.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /departments/1
  # DELETE /departments/1.json
  def destroy
    @department.destroy
    respond_to do |format|
      format.html { redirect_to admin_departments_path, notice: 'Department was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_department
      @department = Department.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def department_params
      params.require(:department).permit(:name, :parent_id, :chief_id, :address_id, :location, :zip, :street, :house, :room, params: [:id, :name, :value, :type])
    end
end

app/controllers/departments_controller.rb
class DepartmentsController < ApplicationController
  def show
    results = Contact.sk_search params[:id]
    @pagy, @results = pagy_searchkick results

    respond_to do |format|
      format.html
      format.turbo_stream
    end
  end
end

app/views/admin/departments/_contacts_form.html.erb
<% phones = f.object.params.where(param_type: "phone") %>
<div class="flex flex-wrap lg:flex-nowrap gap-2 mb-4 items-baseline" data-controller="nested-form" data-nested-form-wrapper-selector-value=".nested-form-wrapper">
  <template data-nested-form-target="template">
    <%= f.fields_for :params, Param.new(param_type: "phone"), child_index: 'NEW_RECORD' do |param_fields| %>
      <%= render "param_form", f: param_fields, placeholder_type: "Тип номера", placeholder_value: "Номер" %>
    <% end %>
  </template>
  <%= label_tag "contact[params_attributes][0][value]", "Контактный телефон:", class: "font-medium min-w-64" %>
  <div class="flex flex-col gap-2 w-full">
    <%= f.fields_for :params, phones do |param_fields| %>
      <%= render "param_form", f: param_fields, placeholder_type: "Тип номера", placeholder_value: "Номер" %>
    <% end %>

    <button type="button" class="btn w-24 ml-auto" data-action="nested-form#add" data-nested-form-target="target">
      Добавить
    </button>
  </div>
</div>

<% emails = f.object.params.where(param_type: "email") %>
<div class="flex flex-wrap lg:flex-nowrap gap-2 mb-4 items-baseline" data-controller="nested-form" data-nested-form-wrapper-selector-value=".nested-form-wrapper">
  <template data-nested-form-target="template">
    <%= f.fields_for :params, Param.new(param_type: "email"), child_index: 'NEW_RECORD' do |param_fields| %>
      <%= render "param_form", f: param_fields, placeholder_type: "Тип e-mail", placeholder_value: "E-mail" %>
    <% end %>
  </template>
  <%= label_tag "contact[params_attributes][#{emails.count}][value]", "Контактный Email:", class: "font-medium min-w-64" %>
  <div class="flex flex-col gap-2 w-full">
    <%= f.fields_for :params, emails do |param_fields| %>
      <%= render "param_form", f: param_fields, placeholder_type: "Тип e-mail", placeholder_value: "E-mail" %>
    <% end %>

    <button type="button" class="btn w-24 ml-auto" data-action="nested-form#add" data-nested-form-target="target">
      Добавить
    </button>
  </div>
</div>

<div class="flex flex-wrap lg:flex-nowrap gap-2 mb-8 items-baseline">
  <%= f.label :address, "Адрес подразделения:", class: "font-medium min-w-64" %>
  <div class="grid gap-2 grow">
    <%= f.text_area :address, class: "form-input min-h-24", data: { controller: "textarea-autogrow", textarea_autogrow_resize_debounce_delay_value: "500" } %>
    <%#= f.select :chief_id, Contact.all.collect {|contact| [ contact, contact.id ] }, { include_blank: true }, class: "form-input grow" %>
  </div>
</div>

app/views/admin/departments/_form.html.erb
<%= form_with model: [:admin, @department] do |f| %>
  <div class="mb-4" 
    data-controller="tabs"
    data-tabs-active-class="[&.active]:text-pb-500 [&.active]:border-pb-500 dark:text-pb-500 dark:border-pb-500">
    
    <div class="border-b border-gray-200 dark:border-gray-700 mb-4">
      <ul class="flex flex-wrap -mb-px text-sm font-medium text-center text-gray-500 dark:text-gray-400">
        <li class="me-2">
          <a href="#" data-action="tabs#profile" class="border-transparent hover:text-gray-600 hover:border-gray-300 dark:hover:text-gray-300 inline-flex items-center justify-center p-4 border-b-2 rounded-t-lg group">
            <svg class="w-4 h-4 me-2" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 20">
              <path d="M10 0a10 10 0 1 0 10 10A10.011 10.011 0 0 0 10 0Zm0 5a3 3 0 1 1 0 6 3 3 0 0 1 0-6Zm0 13a8.949 8.949 0 0 1-4.951-1.488A3.987 3.987 0 0 1 9 13h2a3.987 3.987 0 0 1 3.951 3.512A8.949 8.949 0 0 1 10 18Z"/>
            </svg>
            Информация
          </a>
        </li>
        <li class="me-2">
          <a href="#" data-action="tabs#contacts" class="border-transparent hover:text-gray-600 hover:border-gray-300 dark:hover:text-gray-300 inline-flex items-center justify-center p-4 border-b-2 rounded-t-lg group" data-tabs-target="btn">
            <svg class="w-4 h-4 me-2" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 20">
              <path d="M7.824 5.937a1 1 0 0 0 .726-.312 2.042 2.042 0 0 1 2.835-.065 1 1 0 0 0 1.388-1.441 3.994 3.994 0 0 0-5.674.13 1 1 0 0 0 .725 1.688Z"/>
              <path d="M17 7A7 7 0 1 0 3 7a3 3 0 0 0-3 3v2a3 3 0 0 0 3 3h1a1 1 0 0 0 1-1V7a5 5 0 1 1 10 0v7.083A2.92 2.92 0 0 1 12.083 17H12a2 2 0 0 0-2-2H9a2 2 0 0 0-2 2v1a2 2 0 0 0 2 2h1a1.993 1.993 0 0 0 1.722-1h.361a4.92 4.92 0 0 0 4.824-4H17a3 3 0 0 0 3-3v-2a3 3 0 0 0-3-3Z"/>
            </svg>
            Контакты
          </a>
        </li>
      </ul>
    </div>
  
    <div id="profile" class="flex-column md:flex">
      <%= render "profile_form", f: f %>
    </div>

    <div id="contacts">
      <%= render "contacts_form", f: f %>
    </div>
  </div>

  <div class="flex gap-2 justify-center items-baseline">
    <%= link_to "Отмена", [:admin, :departments], class: "btn", role: "button" %>
    <%= f.button "Сохранить", class: "btn-primary" %>
  </div>
<% end %>

app/views/admin/departments/_profile_form.html.erb
<div class="flex-1">
  <div class="flex flex-wrap lg:flex-nowrap gap-2 mb-4 items-baseline">
    <%= f.label :name, "Наименование:", class: "font-medium min-w-64" %>
    <%= f.text_field :name, class: "form-input grow", placeholder: "Наименование подразделения" %>
  </div>

  <div class="flex flex-wrap lg:flex-nowrap gap-2 mb-4 items-baseline">
    <%= f.label :parent_id, "Родительское подразделения:", class: "font-medium min-w-64" %>
    <%= f.select :parent_id, nested_set_options(Department) {|i| "#{'-' * i.level} #{i.name}" }, { include_blank: true }, class: "form-input grow" %>
  </div>

  <div class="flex flex-wrap lg:flex-nowrap gap-2 mb-8 items-baseline">
    <%= f.label :chief_id, "Руководитель:", class: "font-medium min-w-64" %>
    <%= f.select :chief_id, Contact.all.collect {|contact| [ contact, contact.id ] }, { include_blank: true }, class: "form-input grow", data: { controller: "tom-select" } %>
  </div>
</div>

app/views/admin/departments/edit.html.erb
<% provide :page_title, "Редактирование подразделения" %>

<%= page_title "Редактирование подразделения", [:admin, :departments] %>

<%= render "form" %>

app/views/admin/departments/index.html.erb
<% provide :page_title, "Список подразделений" %>

<%= page_title "Список подразделений" do %>
  <%= link_to [:new, :admin, :department], class: "btn-primary flex flex-nowrap items-center gap-2 w-full justify-center" do %>
    <%= bs_icon 'folder-plus' %>
    Добавить
  <% end %>
<% end %>

<%= fields_for :departments do |f| %>
  <div class="treeview mb-4" data-controller="nested-sortable" data-nested-sortable-handle-value=".handle" data-nested-sortable-resource-name-value="department">
    <%= nested_list Department, item_options: { 'data-sortable-update-url': lambda {|dep| admin_department_path(dep) } }  do |dep| %>
      <%= tag.div class: "group flex items-center gap-1 select-none" do %>
        <%#= bs_icon 'dash-square' %>
        <%#= f.check_box :id, class: "mr-2 align-middle" %>
        <%= tag.span class: "click hover:text-gray-950" do %>
          <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-5 h-5">
            <path stroke-linecap="round" stroke-linejoin="round" d="M3.75 9.776c.112-.017.227-.026.344-.026h15.812c.117 0 .232.009.344.026m-16.5 0a2.25 2.25 0 0 0-1.883 2.542l.857 6a2.25 2.25 0 0 0 2.227 1.932H19.05a2.25 2.25 0 0 0 2.227-1.932l.857-6a2.25 2.25 0 0 0-1.883-2.542m-16.5 0V6A2.25 2.25 0 0 1 6 3.75h3.879a1.5 1.5 0 0 1 1.06.44l2.122 2.12a1.5 1.5 0 0 0 1.06.44H18A2.25 2.25 0 0 1 20.25 9v.776" />
          </svg>
        <% end %>
        <%= tag.span class: "handle hover:text-gray-950" do %>
          <%= bs_icon 'grip-vertical' %>
        <% end if true %>

        <%= tag.div dep.name, class: "flex-auto truncate select-text", title: dep.name %>

        <%= link_to [:edit, :admin, dep], class: "hidden group-hover:block text-pb-400 hover:text-pb-600" do %>
          <%= bs_icon 'pencil-square' %>
        <% end %>
      <% end %>
    <% end %>
  </div>
<% end %>

app/views/admin/departments/new.html.erb
<% provide :page_title, "Новое подразделение" %>

<%= page_title "Новое подразделение", [:admin, :departments] %>

<%= render "form" %>