config/routes.rb
class RestrictedConstraint
  def matches?(request)
    request.path !~ /rails/
  end
end

Rails.application.routes.draw do
  root "phonebook#search"

  get '/', to: 'phonebook#search', as: 'search'
  get '/autocomplete', to: 'phonebook#autocomplete'

  scope :account do
    devise_for :users, path: "", path_names: {
      sign_in: 'login',
      sign_out: 'logout',
      registration: 'signup'
    }
  end

  namespace :api, :defaults => { :format => :json } do 
    namespace :v1 do
      resources :contacts, only: [:index, :show, :create, :destroy, :update], constraints: lambda { |req| ['json', 'xml', 'csv', 'vcf', 'png'].include?(req.format) }
      resource :help, only: [:show, :create, :destroy, :update], constraints: { format: 'html' }
      resource :user, only: [:show, :update], constraints: { format: 'json' }
    end 
  end

  namespace :admin do
    get '/', to: redirect { |p, r| "#{r.url.sub(/(\/)+$/,'')}/users" }

    resources :users, except: %i[show], path_names: { edit: '' }
    resources :contacts, except: %i[show], path_names: { edit: '' }
    resources :departments, except: %i[show], path_names: { edit: '' }
    resources :titles, except: %i[show], path_names: { edit: '' }
    resource :help
    resource :settings, only: %i[show update]
  end

  namespace :profile do
    resource :my_profile
    resources :my_contacts
    resource :settings
  end

  resources :exports, only: %i[index new create show]
  delete '/exports', to: 'exports#destroy_all'
  # resource :settings
  resource :helps, only: %i[show]

  resources :contacts, only: %i[show], path: '', constraints: lambda {|request| Contact.find_by_slug request.params[:id]}
  resources :departments, only: %i[show], path: '', constraints: lambda {|request| Department.find_by_slug request.params[:id]}
  
  get '*path', to: redirect("?q=%{path}"), constraints: RestrictedConstraint.new
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pagy::Backend
  include ActiveStorage::SetCurrent
  
  protect_from_forgery prepend: true
  #protect_from_forgery with: :null_session
  #protect_from_forgery unless: -> { request.format.json? }
  
  layout proc { false if request.xhr? }
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend
  
  def full_title(page_title)
    base_title = Setting.title
    page_title.present? ? "#{page_title} | #{base_title}" : base_title
  end

  def page_title title, back_url = nil, &block
    tag.div class: "sticky top-[-2rem] tall:top-12 pt-6 bg-white z-20" do
      tag.div class: "flex flex-col sm:block my-4 items-between" do
        icon = bs_icon 'chevron-left', '1.2em'
        concat tag.div class: "order-2 float-end flex gap-2 flex-wrap", &block
        concat (tag.div class: "order-1 flex items-center flex-nowrap mb-2 sm:mb-0" do
          concat link_to icon, back_url, class: "btn mr-2", role: "button" if back_url
          concat tag.h1 title, class: "text-3xl font-normal truncate"
        end)
      end
    end
  end

  def react_component(name, props = {})
    content_tag(:div, { id: name, data: { react_props: props } }) do
    end
  end

  def ext_phone(phones)
    #phones.select{ |phone| phone['type'][/^рабочий|^конференция/i] }
    phones.select{ |phone| phone['type'][/^рабочий/i] }
  end

  def int_phone(phones)
    phones.select{ |phone| phone['type'][/^городской/i] }
  end

  def hicom_phone(phones)
    phones.select{ |phone| phone['type'][/^hicom/i] }
  end

  def department_full deps, prev
    return unless block_given?
    deps = department_title deps, prev
    deps.map { |dep| yield(dep) }
  end

  private

  def department_title deps, prev
    deps.each_with_index do |dep, i|
      return deps[i..] unless prev[i] == dep.id
    end
    []
  end
end

app/views/application/_account.html.erb
<div class="relative inline-block text-left text-black" data-controller="dropdown">
  <a href="#menu" class="link_nav flex items-center" data-action="dropdown#toggle click@window->dropdown#hide">
    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-5 h-5 mr-1">
      <path stroke-linecap="round" stroke-linejoin="round" d="M17.982 18.725A7.488 7.488 0 0 0 12 15.75a7.488 7.488 0 0 0-5.982 2.975m11.963 0a9 9 0 1 0-11.963 0m11.963 0A8.966 8.966 0 0 1 12 21a8.966 8.966 0 0 1-5.982-2.275M15 9.75a3 3 0 1 1-6 0 3 3 0 0 1 6 0Z" />
    </svg>
    <%= current_user.contact || current_user.email %>
    <svg class="w-2.5 h-2.5 ms-3" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 10 6">
      <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 1 4 4 4-4"/>
    </svg>
  </a>
  
  <div class="hidden card min-w-[450px] absolute right-0 z-50 my-1 w-full origin-top-right" data-dropdown-target="menu">
    <div class="p-3 flex">
      <div class="mr-4">
        <%= image_tag current_user.contact&.image(:small) || "small_user.png", class: "border p-1 rounded max-w-full h-auto", skip_pipeline: !!current_user.contact&.image(:small) %>
        <%#= image_tag current_user.contact.image.attached? ? current_user.contact.image.variant(:small) : "small_user.png", class: "border p-1 rounded max-w-full h-auto", skip_pipeline: true %>
      </div>
      <div>
        <%= tag.h6 current_user.contact, class: "font-medium mb-2" %>
        <span class="text-sm font-light">
          <%= tag.p current_user.contact&.title %>
          <%= tag.p current_user.contact&.department %>
        </span>
      </div>
    </div>
    <hr>
    <div class="grid grid-cols-2 p-3 gap-2">
      <div>
        <h6 class="font-medium mb-2 text-sm">Мой профиль</h6>
        <nav class="account-menu">
          <%= render "navigation_profile"%>
        </nav>
      </div>
      <%= tag.div do %>
        <h6 class="font-medium mb-2 text-sm">Управление системой</h6>
        <nav class="account-menu">
          <%= render "navigation_admin"%>
        </nav>
      <% end if current_user.has_role?(:admin) %>
    </div>
    <div class="p-3 rounded-b-md bg-gray-100 flex gap-2 justify-between items-baseline text-sm">
      <%= link_to 'Изменить пароль', edit_registration_path(:user), class: "link" %>
      <%= button_to 'Выход', destroy_session_path(:user), method: :delete, class: "btn btn-sm", role: "button" %>
    </div>
  </div>
</div>

app/views/application/_contacts.html.erb
<% session[:current_department] = [] if @pagy.page == 1 %>

<% @results.each do |contact| %>
  <%= render contact.department if contact&.department %>
  <%= render contact if contact %>
<% end %>

app/views/application/_flash.html.slim
- if flash.any?
  .mt-4.alert.alert-warning.alert-dismissible.fade.show
    - flash.each do |name, msg|
      - next unless msg.is_a?(Array) && msg.any? { |x| x.is_a? String } || msg.is_a?(String)
      strong
        =t(name)
        ' :
      - if msg.class == Array
        - msg.each do |message|
          = message if msg.is_a? String
      - else
        = msg

    button.close type="button" data-dismiss="alert" aria-label="Close"
      span aria-hidden="true" &times;

app/views/application/_footer.html.erb
<footer class="tall:fixed bottom-0 left-0 right-0 bg-white border-t">
  <div class="mx-auto max-w-screen-xl flex justify-center md:justify-between px-4 py-2 text-[0.875rem]">
    <p class="hidden md:block"><%= Setting.title %></p>
    <p class="text-center">© Телефонный справочник [версия 3.5]</p>
  </div>
</footer>

app/views/application/_header.html.erb
<header class="static tall:sticky top-0 left-0 right-0 bg-gradient-to-b from-pb-400 to-pb-700 via-pb-600 text-gray-50 z-50">
  <div class="mx-auto max-w-screen-xl flex items-center justify-center h-20 px-4">
    <%= render "logo" %>

    <% if user_signed_in? %>
      <nav class="hidden md:flex ml-auto space-x-4">
        <%= render "navigation_main" %>
      </nav>

      <button class="ml-auto md:hidden">
        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
          <path stroke-linecap="round" stroke-linejoin="round" d="M3.75 6.75h16.5M3.75 12h16.5m-16.5 5.25h16.5" />
        </svg>
      </button>
    <% end %>
  </div>
</header>

app/views/application/_links.html.erb
<div class="mt-3 text-center text-sm leading-5">
  <% if devise_mapping.confirmable? && controller_name != 'confirmations' %>
    <div>
      <%= link_to "Подтвердить аккаунт", new_confirmation_path(resource, resource_name), class: "link font-medium" %>
    </div>
  <% end %>

  <% if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
    <div>
      <%= link_to "Разблокировать аккаунт", new_unlock_path(resource_name), class: "link font-medium" %>
    </div>
  <% end %>

  <% if devise_mapping.omniauthable? %>
    <div>
      <% resource_class.omniauth_providers.each do |provider| %>
        <%= link_to "Войти через #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), class: "link font-medium" %>
      <% end %>
    </div>
  <% end %>
</div>

app/views/application/_logo.html.erb
<%= link_to root_path, class: "link-no-decorate" do %>
  <% if user_signed_in? %>
    <div class="flex items-center">
      <%= image_tag "logo.png", class: "mr-2" %>
      <div class="flex flex-col uppercase">
        <span class="text-[1.4rem] tracking-[2px] leading-[1.5rem]">Телефонный</span>
        <span class="text-[0.7rem] tracking-[8px] leading-[1rem]">справочник</span>
      </div>
    </div>
  <% else %>
    <div class="flex flex-row uppercase items-center justify-center w-full">
      <span class="text-[1.3rem] tracking-[-1px] leading-[1.5rem]">Телефонный</span>
      <%= image_tag "logo.png", class: "mx-1" %>
      <span class="text-[1.3rem] tracking-[-1px] leading-[1.5rem]">справочник</span>
    </div>
  <% end %>
<% end %>

app/views/application/_navigation_admin.html.erb
<%= link_to admin_users_path, class: "link#{request.path =~ /^#{admin_users_path}/ ? ' active' : ''}" do %>
  Пользователи
  <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
    <path stroke-linecap="round" stroke-linejoin="round" d="m8.25 4.5 7.5 7.5-7.5 7.5" />
  </svg>
<% end if current_user.has_role?(:admin) %>

<%= link_to admin_contacts_path, class: "link#{request.path =~ /^#{admin_contacts_path}/ ? ' active' : ''}" do %>
  Управление контактами
  <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
    <path stroke-linecap="round" stroke-linejoin="round" d="m8.25 4.5 7.5 7.5-7.5 7.5" />
  </svg>
<% end %>

<%= link_to admin_departments_path, class: "link#{request.path =~ /^#{admin_departments_path}/ ? ' active' : ''}" do %>
  Структура подразделений
  <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
    <path stroke-linecap="round" stroke-linejoin="round" d="m8.25 4.5 7.5 7.5-7.5 7.5" />
  </svg>
<% end %>

<%= link_to admin_titles_path, class: "link#{request.path =~ /^#{admin_titles_path}/ ? ' active' : ''}" do %>
  Список должностей
  <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
    <path stroke-linecap="round" stroke-linejoin="round" d="m8.25 4.5 7.5 7.5-7.5 7.5" />
  </svg>
<% end %>

<%= link_to admin_help_path, class: "link#{request.path =~ /^#{admin_help_path}/ ? ' active' : ''}" do %>
  Справка по использованию
  <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
    <path stroke-linecap="round" stroke-linejoin="round" d="m8.25 4.5 7.5 7.5-7.5 7.5" />
  </svg>
<% end if current_user.has_role?(:admin) %>

<%= link_to admin_settings_path, class: "link#{request.path =~ /^#{admin_settings_path}/ ? ' active' : ''}" do %>
  Глобальные настройки
  <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
    <path stroke-linecap="round" stroke-linejoin="round" d="m8.25 4.5 7.5 7.5-7.5 7.5" />
  </svg>
<% end if current_user.has_role?(:admin) %>

app/views/application/_navigation_main.html.erb
<%= link_to root_path, class: "link_nav flex items-center #{request.path == "/" ? ' link-active' : ''}" do %>
  <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-5 h-5 mr-1">
    <path stroke-linecap="round" stroke-linejoin="round" d="M12 6.042A8.967 8.967 0 0 0 6 3.75c-1.052 0-2.062.18-3 .512v14.25A8.987 8.987 0 0 1 6 18c2.305 0 4.408.867 6 2.292m0-14.25a8.966 8.966 0 0 1 6-2.292c1.052 0 2.062.18 3 .512v14.25A8.987 8.987 0 0 0 18 18a8.967 8.967 0 0 0-6 2.292m0-14.25v14.25" />
  </svg>
  Контакты
<% end %>

<%= link_to helps_path, class: "link_nav flex items-center #{request.path == "/helps" ? ' link-active' : ''}" do %>
  <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-5 h-5 mr-1">
    <path stroke-linecap="round" stroke-linejoin="round" d="M9.879 7.519c1.171-1.025 3.071-1.025 4.242 0 1.172 1.025 1.172 2.687 0 3.712-.203.179-.43.326-.67.442-.745.361-1.45.999-1.45 1.827v.75M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0Zm-9 5.25h.008v.008H12v-.008Z" />
  </svg>
  Справка
<% end %>

<%#= link_to settings_path, class: "link_nav flex items-center #{request.path == "/settings" ? ' link-active' : ''}" do %>
  <%# <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-5 h-5 mr-1">
    <path stroke-linecap="round" stroke-linejoin="round" d="M9.594 3.94c.09-.542.56-.94 1.11-.94h2.593c.55 0 1.02.398 1.11.94l.213 1.281c.063.374.313.686.645.87.074.04.147.083.22.127.325.196.72.257 1.075.124l1.217-.456a1.125 1.125 0 0 1 1.37.49l1.296 2.247a1.125 1.125 0 0 1-.26 1.431l-1.003.827c-.293.241-.438.613-.43.992a7.723 7.723 0 0 1 0 .255c-.008.378.137.75.43.991l1.004.827c.424.35.534.955.26 1.43l-1.298 2.247a1.125 1.125 0 0 1-1.369.491l-1.217-.456c-.355-.133-.75-.072-1.076.124a6.47 6.47 0 0 1-.22.128c-.331.183-.581.495-.644.869l-.213 1.281c-.09.543-.56.94-1.11.94h-2.594c-.55 0-1.019-.398-1.11-.94l-.213-1.281c-.062-.374-.312-.686-.644-.87a6.52 6.52 0 0 1-.22-.127c-.325-.196-.72-.257-1.076-.124l-1.217.456a1.125 1.125 0 0 1-1.369-.49l-1.297-2.247a1.125 1.125 0 0 1 .26-1.431l1.004-.827c.292-.24.437-.613.43-.991a6.932 6.932 0 0 1 0-.255c.007-.38-.138-.751-.43-.992l-1.004-.827a1.125 1.125 0 0 1-.26-1.43l1.297-2.247a1.125 1.125 0 0 1 1.37-.491l1.216.456c.356.133.751.072 1.076-.124.072-.044.146-.086.22-.128.332-.183.582-.495.644-.869l.214-1.28Z" />
    <path stroke-linecap="round" stroke-linejoin="round" d="M15 12a3 3 0 1 1-6 0 3 3 0 0 1 6 0Z" />
  </svg>
  Настройки %>
<%# end %>

<%= render "account" if current_user %>

app/views/application/_navigation_profile.html.erb
<%= link_to profile_my_profile_path, class: "link#{request.path =~ /^#{profile_my_profile_path}/ ? ' active' : ''}" do %>
  Обо мне
  <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
    <path stroke-linecap="round" stroke-linejoin="round" d="m8.25 4.5 7.5 7.5-7.5 7.5" />
  </svg>
<% end if current_user && current_user.contact %>

<%= link_to profile_my_contacts_path, class: "link#{request.path =~ /^#{profile_my_contacts_path}/ ? ' active' : ''}" do %>
  Мои контакты
  <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
    <path stroke-linecap="round" stroke-linejoin="round" d="m8.25 4.5 7.5 7.5-7.5 7.5" />
  </svg>
<% end %>

<%#= link_to "Отзывы и предложения", contacts_path, class: "link" %>

<%= link_to profile_settings_path, class: "link#{request.path =~ /^#{profile_settings_path}/ ? ' active' : ''}" do %>
  Настройки
  <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
    <path stroke-linecap="round" stroke-linejoin="round" d="m8.25 4.5 7.5 7.5-7.5 7.5" />
  </svg>
<% end %>

app/views/application/_params.html.erb
<% model_params = contact.params.select{|prm| prm.param_type == param_type} %>
<% model_name = contact.model_name.singular %>

<div class="flex flex-col gap-2 w-full">
  <% (!model_params.blank? && model_params || [{name: nil, param_type: :phone, value: nil}]).each_with_index do |param, i| %>
    <%= hidden_field_tag "#{model_name}[params][][id]", param[:id], id: nil if param[:id] %>
    <%= hidden_field_tag "#{model_name}[params][][type]", param_type, id: nil %>
    <div class="flex gap-2">
      <%= select_tag "#{model_name}[params][][name]", options_for_select(Param.send("all_#{param_type}_types", default_types), param[:name]), id: nil, include_blank: true, data: {role: "select2", placeholder: type_name, tags: true}, class: "form-input" %>
      <%= text_field_tag "#{model_name}[params][][value]", param[:value], id: "#{model_name}_params_#{param_type}_#{i}", class: "form-input", placeholder: type_value %>
    </div>
  <% end %>
</div>

app/views/application/_search.html.erb
<% url ||= url_for(action: 'index') %>
<% autofocus ||= false %>

<div class="sticky top-2 tall:top-24 mt-12 mb-8 z-20">
  <%= form_with url:, method: "GET", class: "relative group", data: { controller: "search autocomplete", autocomplete_url_value: "/autocomplete" } do |f| %>
    <div role="combobox">
      <%= f.text_field :q,
        class: "relative w-full pl-4 pr-[70px] py-2 text-xl border border-gray-300 rounded-md focus:shadow-[0_0_0_0.25rem] focus:shadow-pb-300/50 z-10",
        placeholder: "Быстрый поиск контактов",
        autocomplete: "off",
        data: { search_target: "input", autocomplete_target: "input" },
        autofocus:
      %>
      <div class="absolute top-1 right-1 h-[38px] pr-2 flex gap-3 items-center bg-white z-20">
        <svg
          class="h-6 cursor-pointer text-gray-400 group-has-[:placeholder-shown]:hidden click"
          focusable="false"
          role="img"
          xmlns="http://www.w3.org/2000/svg"
          viewBox="0 0 320 512"
          data-search-target="clear"
          >
          <path fill="currentColor" d="M310.6 361.4c12.5 12.5 12.5 32.75 0 45.25C304.4 412.9 296.2 416 288 416s-16.38-3.125-22.62-9.375L160 301.3L54.63 406.6C48.38 412.9 40.19 416 32 416S15.63 412.9 9.375 406.6c-12.5-12.5-12.5-32.75 0-45.25l105.4-105.4L9.375 150.6c-12.5-12.5-12.5-32.75 0-45.25s32.75-12.5 45.25 0L160 210.8l105.4-105.4c12.5-12.5 32.75-12.5 45.25 0s12.5 32.75 0 45.25l-105.4 105.4L310.6 361.4z"></path>
        </svg>
        <%= f.button name: nil, class: "click" do %>
          <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16" fill="currentColor" class="size-6 text-gray-400">
            <path d="M3.75 2A1.75 1.75 0 0 0 2 3.75v1.5a.75.75 0 0 0 1.5 0v-1.5a.25.25 0 0 1 .25-.25h1.5a.75.75 0 0 0 0-1.5h-1.5ZM10.75 2a.75.75 0 0 0 0 1.5h1.5a.25.25 0 0 1 .25.25v1.5a.75.75 0 0 0 1.5 0v-1.5A1.75 1.75 0 0 0 12.25 2h-1.5ZM3.5 10.75a.75.75 0 0 0-1.5 0v1.5c0 .966.784 1.75 1.75 1.75h1.5a.75.75 0 0 0 0-1.5h-1.5a.25.25 0 0 1-.25-.25v-1.5ZM14 10.75a.75.75 0 0 0-1.5 0v1.5a.25.25 0 0 1-.25.25h-1.5a.75.75 0 0 0 0 1.5h1.5A1.75 1.75 0 0 0 14 12.25v-1.5ZM8 10a2 2 0 1 0 0-4 2 2 0 0 0 0 4Z" />
          </svg>
        <% end %>
      </div>
      <div class="absolute bg-white pt-2 rounded-b-lg border-b border-x border-gray w-full drop-shadow-md hidden has-[ul]:block z-5" data-autocomplete-target="results"></div>
    </div>
  <% end %>
</div>

app/views/application/_side_panel.html.erb
<div class="sticky top-28 mb-4">
  <%= yield(:left_menu_before) %>

  <% if user_signed_in? %>
    <div class="mt-4">
      <h6 class="text-xl font-light py-2">Мой профиль</h6>
      <nav class="left-menu">
        <%= render "navigation_profile"%>
      </nav>
    </div>
  <% end %>

  <% if current_user && (current_user.has_role?(:admin) || current_user.has_role?(:manager)) %>
    <div class="mt-4">
      <h6 class="text-xl font-light py-2">Управление системой</h6>
      <nav class="left-menu">
        <%= render "navigation_admin" if current_user && (current_user.has_role?(:admin) || current_user.has_role?(:manager)) %>
      </nav>
    </div>
  <% end %>
  
  <%= yield(:left_menu_after) %>
</div>